addSbtPlugin("org.typelevel"  % "sbt-typelevel"          % "0.6.4")
addSbtPlugin("org.typelevel"  % "sbt-typelevel-site"     % "0.6.4")
addSbtPlugin("org.typelevel"  % "sbt-typelevel-scalafix" % "0.6.4")
addSbtPlugin("org.scala-js"   % "sbt-scalajs"            % "1.14.0")
addSbtPlugin("org.scalameta"  % "sbt-mdoc"               % "2.5.1")
addSbtPlugin("com.github.sbt" % "sbt-unidoc"             % "0.5.0")
