@host = http://localhost:19876

###
# @name: List all flags
#
GET {{ host }}/admin/flags/

###
# @name: Get flag by id

@featureId = feature-2

GET {{ host }}/admin/flags/{{featureId}}

###
# @name: Update flag by id

PUT {{ host }}/admin/flags/{{featureId}}
Content-Type: application/json

{
  "status": "enabled"
}
